### ISSUE TITLE
Automatic check for API version?

### ISSUE THREAD

**Issue by loial** [mgejke/asyncsector#12]
Quite frequent api-updates from Sector alarm... Now its v1_1_72, seems like it has changed every week or so during the summer...

Since it's seems api is unavailable unless exact version is specified, (every api change breaks without this change), maybe we could try to check for version on first fail and autoupdate accordingly or something?

I could try to work on a PR, but I'd like to hear some other thoughts on this...

Should we assume Sector follows Semantic Versioning, and asume no breaking changes unless v1_x_x becomes v2_x_x, or limit it down to minor level v1_1_x?

And is there anywhere to store the "current" version, so we don't need to check this on every call?

**Comment by sebastian-steinmann** [comment]
Involves html scraping somethings thats been banned by Home Assistant, but this is a custom-component, so could work.
Anyone up to the task?

**Comment by loial** [comment]
Been thinking about this, and can try to hack something tonight. 

Again thinking aloud:
Let's keep the current behaviour, by using --version=v1_x_x. But by adding --version=auto, the script will do an initial request to fetch the version code, an use for the rest of the process. So this will be an opt-in.
Let's also return the api version number in the response payload. Also, on "INVALID VERSION" return a hint suggsting the new version code.

Then, any implementation, such as the hass component, can also do an opt-in "auto" config, storing the api code in a state or something. So normal operation provides the version code (to prevent the initial auto-request) Then either autoupdate the state on failed requests, or notify the user that the API has changed and suggest an appropriate update.

Thus, this wouldn't change current behaviour, the components won't "rely" on scraping, and let's the users either be notified of changed api, or ootionally automate the process.

I'll try to play around with this later tonight...

**Comment by loial** [comment]
So, PR #13 is committed. Still thinking about how to smoothly integrate it into hass-sectoralarm. Also did not do anything about providing apiversion as part of response payload...

**Comment by loial** [comment]
Oh.., wait... rookie mistake... put the logic in the _main_ wrapper instead of the constructor function... I should tweak that...

**Comment by loial** [comment]
There... 😳 #14

**Comment by mgejke** [comment]
Thanks, merged!
