### ISSUE TITLE
Version mismatch causes issues

### ISSUE THREAD

**Issue by Pretagonist** [mgejke/asyncsector#5]
It seems the web interfaces uses 1.1.66 while current code tries 1.1.64

**Comment by willeraab** [comment]
Current version now (used by web) is 1.1.67. However when I change this I still get "INVALID_VERSION" when trying to request temperatures (panel is working though).

**Comment by willeraab** [comment]
I have created a pull request that will solve this issue (make it up to 1.1.67).

**Comment by sebastian-steinmann** [comment]
This is solved now right?

**Comment by mgejke** [comment]
Yes!
